import { MetadataRoute } from "next";

/**
 * robots.txt, generated by Next so it stays in sync with the app. Supersedes the old
 * static public/robots.txt. Allows the public marketing pages and disallows the
 * private/app areas (admin, account, audit results, auth, and the API).
 */
export default function robots(): MetadataRoute.Robots {
  const baseUrl = process.env.NEXT_PUBLIC_APP_URL || "https://siteiq.monkata.ai";
  return {
    rules: {
      userAgent: "*",
      allow: "/",
      disallow: [
        "/admin",
        "/account",
        "/audit",
        "/audits",
        "/login",
        "/signup",
        "/api",
      ],
    },
    sitemap: `${baseUrl}/sitemap.xml`,
  };
}
